# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/e/learn/SECOND_DOWN/oop/cardgame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/e/learn/SECOND_DOWN/oop/cardgame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/learn/SECOND_DOWN/oop/cardgame/CMakeFiles /mnt/e/learn/SECOND_DOWN/oop/cardgame/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/e/learn/SECOND_DOWN/oop/cardgame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

cardgame/game/card.o: cardgame/game/card.cpp.o

.PHONY : cardgame/game/card.o

# target to build an object file
cardgame/game/card.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/game/card.cpp.o
.PHONY : cardgame/game/card.cpp.o

cardgame/game/card.i: cardgame/game/card.cpp.i

.PHONY : cardgame/game/card.i

# target to preprocess a source file
cardgame/game/card.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/game/card.cpp.i
.PHONY : cardgame/game/card.cpp.i

cardgame/game/card.s: cardgame/game/card.cpp.s

.PHONY : cardgame/game/card.s

# target to generate assembly for a file
cardgame/game/card.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/game/card.cpp.s
.PHONY : cardgame/game/card.cpp.s

cardgame/game/deck.o: cardgame/game/deck.cpp.o

.PHONY : cardgame/game/deck.o

# target to build an object file
cardgame/game/deck.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/game/deck.cpp.o
.PHONY : cardgame/game/deck.cpp.o

cardgame/game/deck.i: cardgame/game/deck.cpp.i

.PHONY : cardgame/game/deck.i

# target to preprocess a source file
cardgame/game/deck.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/game/deck.cpp.i
.PHONY : cardgame/game/deck.cpp.i

cardgame/game/deck.s: cardgame/game/deck.cpp.s

.PHONY : cardgame/game/deck.s

# target to generate assembly for a file
cardgame/game/deck.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/game/deck.cpp.s
.PHONY : cardgame/game/deck.cpp.s

cardgame/game/main.o: cardgame/game/main.cpp.o

.PHONY : cardgame/game/main.o

# target to build an object file
cardgame/game/main.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/game/main.cpp.o
.PHONY : cardgame/game/main.cpp.o

cardgame/game/main.i: cardgame/game/main.cpp.i

.PHONY : cardgame/game/main.i

# target to preprocess a source file
cardgame/game/main.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/game/main.cpp.i
.PHONY : cardgame/game/main.cpp.i

cardgame/game/main.s: cardgame/game/main.cpp.s

.PHONY : cardgame/game/main.s

# target to generate assembly for a file
cardgame/game/main.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/game/main.cpp.s
.PHONY : cardgame/game/main.cpp.s

cardgame/player_web/player.o: cardgame/player_web/player.cpp.o

.PHONY : cardgame/player_web/player.o

# target to build an object file
cardgame/player_web/player.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/player_web/player.cpp.o
.PHONY : cardgame/player_web/player.cpp.o

cardgame/player_web/player.i: cardgame/player_web/player.cpp.i

.PHONY : cardgame/player_web/player.i

# target to preprocess a source file
cardgame/player_web/player.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/player_web/player.cpp.i
.PHONY : cardgame/player_web/player.cpp.i

cardgame/player_web/player.s: cardgame/player_web/player.cpp.s

.PHONY : cardgame/player_web/player.s

# target to generate assembly for a file
cardgame/player_web/player.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/cardgame/player_web/player.cpp.s
.PHONY : cardgame/player_web/player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... cardgame/game/card.o"
	@echo "... cardgame/game/card.i"
	@echo "... cardgame/game/card.s"
	@echo "... cardgame/game/deck.o"
	@echo "... cardgame/game/deck.i"
	@echo "... cardgame/game/deck.s"
	@echo "... cardgame/game/main.o"
	@echo "... cardgame/game/main.i"
	@echo "... cardgame/game/main.s"
	@echo "... cardgame/player_web/player.o"
	@echo "... cardgame/player_web/player.i"
	@echo "... cardgame/player_web/player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

